### ISSUE TITLE
Find additional experts to support ACF2/TSS systems

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/community#970]
**Is your feature request related to a problem or limitation? Please describe.**

We currently have several change requests on the ACF2/TSS systems pending, would like to seek possibilities to find more experts who can help on maintaining the 2 systems.

**Additional context**

Currently Marist college IT support handles z/OS with RACF security system and image level changes (including provision, backup, restore, etc). All ACF2/TSS change requests are handled by experts from Broadcom.

@MarkAckert @balhar-jakub

**Comment by balhar-jakub** [comment]
This should be resolved by the ACF2/TSS on the Marist receiving the standard Broadcom Support instead of depending on specific person.

**Comment by balhar-jakub** [comment]
@jackjia-ibm Could you verify whether now you are able to get the support needed for these two ESMs via standard Broadcom Support?

**Comment by jalel01** [comment]
hi @jackjia-ibm are you now unblocked?

**Comment by jackjia-ibm** [comment]
Sorry @jalel01 @balhar-jakub it's not fully solved yet. We had a meeting last week and there are some action items we need to take.

FYI @pdubz3 @MarkAckert this is the item we are tracking the progress and there are 2 other items are blocked by this.

**Comment by jackjia-ibm** [comment]
Thanks Mike and Mark!

**Comment by jackjia-ibm** [comment]
Thanks Mike and Mark for handling the ticket and work on the 2 systems.

@jalel01 @balhar-jakub I think all changes we need on ACF2/TSS are applied (including https://github.com/zowe/zowe-install-packaging/issues/1779, https://github.com/zowe/zowe-install-packaging/issues/1778 and `APIML.SERVICES` profile for `ZOWE` class. Could you please verify with the team if there are anything missing? Thanks a lot!

**Comment by balhar-jakub** [comment]
@boris-bc This old issue may be relevant to some of the problems experienced in the last few months and also probably should be part of the discussions on how much we can do concerning System level testing in the open community.

**Comment by balhar-jakub** [comment]
Closing as resolved, Mark is able to manage operations and Broadcom is willing to provide support via official support when needed by Zowe to Mark.
